### ISSUE TITLE
Uncaught TypeError: editor.getSelection is not a function

### ISSUE THREAD

**Issue by el-musleh** [expandoco/expando-atom#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [expando-atom](https://github.com/expandoco/expando-atom) package, v0.0.17
### Stack Trace

Uncaught TypeError: editor.getSelection is not a function

```
At /C:/Users/moham/.atom/packages/expando-atom/lib/expando.coffee:24

TypeError: editor.getSelection is not a function
    at Object.module.exports.expand (file:///C:/Users/moham/.atom/packages/expando-atom/lib/expando.coffee:20:24)
    at atom-text-editor.<anonymous> (file:///C:/Users/moham/.atom/packages/expando-atom/lib/expando.coffee:8:65)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\moham\AppData\Local\atom\app-1.2.0\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\moham\AppData\Local\atom\app-1.2.0\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\moham\AppData\Local\atom\app-1.2.0\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\moham\AppData\Local\atom\app-1.2.0\resources\app.asar\src\atom-environment.js:990:28)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (C:\Users\moham\AppData\Local\atom\app-1.2.0\resources\atom.asar\renderer\api\lib\ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\moham\AppData\Local\atom\app-1.2.0\resources\atom.asar\renderer\api\lib\remote.js:138:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\moham\AppData\Local\atom\app-1.2.0\resources\app.asar\src\context-menu-manager.js:156:33)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (C:\Users\moham\AppData\Local\atom\app-1.2.0\resources\app.asar\src\window-event-handler.js:252:47)
    at HTMLDocument.<anonymous> (C:\Users\moham\AppData\Local\atom\app-1.2.0\resources\app.asar\src\window-event-handler.js:3:61)
```
### Commands

```
     -1:43.8.0 core:paste (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:40.6.0 core:delete (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -1:19.9.0 core:paste (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:02.0 core:move-left (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:01.1.0 core:save (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:40.7.0 data-atom:execute (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:15.2.0 data-atom:toggle-results-view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:07.7.0 expando:expand (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-python, v0.10.3
autoupdate-packages, v1.3.0
color-picker, v2.0.13
data-atom, v0.14.1
doctrine, v0.3.0
epitech-headers, v0.2.8
epoch-converter, v0.1.0
expando-atom, v0.0.17
jade-autocompile, v0.6.5
language-livescript-edge, v1.0.2
latex, v0.28.2
minimap, v4.16.0
pigments, v0.18.1
statusbar-datetime, v0.9.7
travis-ci-status, v0.18.0
tree-view-finder, v0.2.1
unitjs, v1.0.0
up2date, v0.1.0
vim-mode, v0.63.0
w3c-validation, v0.2.0

# Dev
No dev packages
```

**Comment by ken0nek** [comment]
I also got the same error as yours :(

Atom: 1.2.4
OS: Yosemite

**Comment by marktucks** [comment]
I have a fix for this but can't seem to send a Fork request.
